### ISSUE TITLE
Decide Repository Standard Development Lifecycle (SDLC)

### ISSUE THREAD

**Issue by TheLarkInn** [webpack-contrib/organization#1]
@webpack-contrib/admin-team Here is a checklist of items to be decided and implemented. Probably need to break them out into separate issues, etc. Feel free to add anything additional. 

- [ ] Decide and Document everything below in Org README.md
  - [x] Decide on README Template
     - Readme template added to all repos. Template comes with defaults.
  - [x] Decide on Lint Standards
     - See https://github.com/webpack-contrib/eslint-config-webpack
  - [x] Decide on Style Standards
  - [x] Decide on Test Standards
     - Tests will be driven by Jest, conversion is a part of `webpack-defaults` upgrade
  - [x] Decide on EditorConfig
     - Generated by `webpack-defaults`
  - [x] Decide on Issue Label Standards
  - [x] Create Loader Template (Something we use to validate repo's applying, as well as resource for those looking to create a new one).
  - [x] Create Plugin Template
  - [x] Implement Commitizen, semantic-release, etc. (Continuous Deployment + Changelog Generation)
  - [x] Use https://github.com/sapegin/mrm

**Comment by ericclemmons** [comment]
Reference:
> https://webpack.slack.com/archives/webpack-contrib-team/p1485366061000139

It'd be useful to finalize each one of these steps **by migrating an existing repo** to the new standard, then leveraging this PR to abstract the workflow out to something that individuals could reliably apply elsewhere.

There are some more repos (loaders & plugins) to be moved to this org before we can choose one to solve these for.

**Comment by joshwiens** [comment]
@ericclemmons - We have a bit of discussion around the project template which has some minimal babel. You have any opinions on babel plugins / ecma features before I get too far into throwing up a p.o.c

**Comment by joshwiens** [comment]
As far as readme template, we for the most part have that already. Michael and Kees put a bunch of time / iterations into the readme thing already.

**Comment by bebraw** [comment]
It would be good to put emphasis on documentation and introspection. I've been doing this at [purifycss-webpack](https://github.com/webpack-contrib/purifycss-webpack) using JSON Schema. This comes with a couple of great benefits:

* It will fail hard if you try to pass invalid properties to it (wrong name, type, etc.). This catches some common errors. -> Less questions about usage.
* This allows introspection. I plan to write a little script to generate readme options based on the schema (one place to maintain) based on this idea.
* Ideally we could do JSON Schema -> type definition so IDEs can pick up the options. I'm not exactly sure how to pull this off, but maybe JSON Schema -> TypeScript would do the trick?

If we agree on a good standard, then you could literally ask a plugin/loader what kind of properties it provides using a REPL. This won't solve all of the documentation need, but I think this would be a good step as now the situation is a little haphazard at best. If you push documentation to forefront like this, at least properties get documented.

**Comment by joshwiens** [comment]
Style Standards - Lets start from here ...

- JavaScript Standard
- Eslint Recommended 

If there is another fork in the road, we should add it to the high level choice and refine from there.

**Comment by bebraw** [comment]
@d3viant0ne I've stuck with ESLint Airbnb with minor modifications, but it's not a big thing for me to adapt to whatever you choose.

**Comment by joshwiens** [comment]
I don't have a strong preference either way (outside of double quotes need to die), so long as we pick one and stick with it.

**Comment by sapegin** [comment]
ESLint:recommended has no code style rules. Standard and AirBnb have. No semicolons vs. semicolons ;-)

**Comment by joshwiens** [comment]
Yeah, that one ^^

**Comment by TheLarkInn** [comment]
Alright, we can leave it to a vote, I like those. Style is style. It should be readable and consistent, and work in "use strict" (as we will probably update these to node 4.3 compat). 

With that in mind, I'd say airbnb-whatever over standard (semi's are mildly important to me).

**Comment by joshwiens** [comment]
@TheLarkInn - There will be minimal babel, getting down to 4.3 won't be an issue.

As for the style, it will reside [here](https://github.com/webpack-contrib/eslint-config-webpack). Will update here when ready for discussion, I have some tweaking to do and an example / test module to create yet.

**Comment by SpaceK33z** [comment]
Okay, using eslint-config-airbnb as a base seems like a good idea. I've been doing that for a few years now too at my work, see [eslint-config-codeyellow](https://github.com/CodeYellowBV/eslint-config-codeyellow) (I don't mean to say to use this, but perhaps you could get some ideas out of this). Airbnb's config is great but sometimes is REALLY REALLY strict.

**Comment by bebraw** [comment]
@SpaceK33z Yup. We'll drop JSX and React specific bits from it and add a couple of webpack specific rules. I think that will work as a starting point.

**Comment by joshwiens** [comment]
I have this almost done already for use to refine. It is as discussed, airbnb-base (no react) plus import without all the react bits & eslint deprecated rules still in airbnb-base. I just need to add the test app to it, should be done by mid-day.

**Comment by joshwiens** [comment]
One more thing to add to the decision list - I propose we disable `merge commits` and all pull requests are merged with `Squash and merge`. It gives maintainers the opportunity to format commit messages if need be and the github history ends up cleaner.

**Comment by bebraw** [comment]
Any ideas on how to vote on the remaining issues? Google poll or some such?

**Comment by joshwiens** [comment]
Individual issues and thumbs up or down? I really wish they would put proper voting into issues as an option on creation.

**Comment by bebraw** [comment]
@d3viant0ne Since you do thumbs up/down per comment, that would be one way. Still a little kludgy. I guess we need a shared document somewhere where we can tally.

**Comment by joshwiens** [comment]
Yeah, it's  far from an optimal solution. A google poll is probably a better idea if we don't mind going outside of github.

**Comment by dmitriid** [comment]
> Decide on README Template
> Readme template added to all repos. Template comes with defaults.

Meanwhile: https://github.com/webpack/webpack.js.org/issues/1076

**Comment by dmitriid** [comment]
I've also looked through several repos, and I think I've seen the README template in use (I don't know the what the actual template is).

The template lacks an important section: `Introduction/What does this thing do`. 

- `extract-text-webpack-plugin` has it in usage, after installation instructions and a long-ish chunk of example code and 
- `css-loader` puts it in Usage
- `style-loader` has it right after the name
- `file-loader` hopes you understand what it does from the name and code examples
- `sass-loader` has it right after the name

And that's just the five pinned repos from `webpack-contrib`. It's often even worse for other repos (see linked issue)

**Comment by joshwiens** [comment]
@dmitriid - Valid point. The template being referenced exists in `webpack-defaults`

https://github.com/webpack-contrib/webpack-defaults/tree/master/templates

We are currently upgrading everything to defaults, I will see the that readme.md gets updates per your suggestion as we work through the upgrades for each repo. 

//cc @bebraw @michael-ciniawsky

**Comment by michael-ciniawsky** [comment]
@dmitriid 👍 Pick one and update to match the template structure, the templates lack the options section and the options table I send PR later :)

**Comment by deemstone** [comment]
Could we describing the input&output of each loaders in their documents, or by some kind of structured meta.

like this: 

loader | input => output
 ----  | ---- 
 postcss-loader  |  css/scss  =>  css 
 style-loader  |  css => js + file(.css) 
 extract-loader  |  js => raw 
 file-loader  |  raw => js(url) + file(raw) 
 babel-loader  |  js(ES5/6)  => js(ES5) 

Because, I always be confused when setting up new webpack config for different project (for different tech stack : scss/less/jade/angular/.... ), and forgot what each of these loaders does, how combine these loaders to work together. It's nearly never be modified after we done this config (let it work and forgot it). When the next project come, I always need spending time on documents of each loaders ... like the first time learning webpack.

> Refer to the pipe design by Gulp, has this benefit over Grunt.

And if we got this meta info, we could build GUI to visualize the good fit between the loaders. We even can build tools generating config automaticaly.

Sorry for my poor English. I hope I already made it clear.

**Comment by michael-ciniawsky** [comment]
Resolved by `webpack-defaults`, please open an issue there in case something is still missing or needs to be changed

**Comment by naGILLWON** [comment]
- @

**Comment by naGILLWON** [comment]
na

**Comment by david-fong** [comment]
> Resolved by `webpack-defaults`, please open an issue there in case something is still missing or needs to be changed

A link for the lazy (like me): [`webpack-defaults`](https://github.com/webpack-contrib/webpack-defaults)
