### ISSUE TITLE
Add gzip-loader.

### ISSUE THREAD

**Issue by jdalton** [webpack-contrib/organization#10]
The Lodash v5 package will contain gzipped modules and folks will want to bundle them. I'll also be releasing the gzip module loader for other folks to publish gzip compressed packages, so the usage will expand beyond that of Lodash. With that in mind, I'd like to add [gzip-loader](https://github.com/jdalton/gzip-loader) to the webpack-contib org.

**Comment by joshwiens** [comment]
Short answer, yes. The only question before it's transfered is how do you want the maintenance handled. The choice doesn't matter, we just like to be clear on expectations before a lib is transferred.

1.) You continue to maintain and the org-maintainers help if requested. e.g. `grunt-webpack`
2.) You are lead maintainer and the org-maintainers assist. e.g `sass-loader`
3.) Hand off to org-maintainers and you help time permitting. e.g.`css-loader`

- Before `gzip-loader` is moved, grant `bebraw` & `d3viant0ne` owner access in npm.
  - regardless of the maint. option you chose, we have a support requirement from JS Foundation and need to be able to publish incase you are unable to for any reason.
- The repo already checks all the boxes as for acceptance in respect to code & tests.
- Repo license complies with JSF licensing requirements & has JSF `LICENSE` committed by existing owner.

As probably already know, you can't directly transfer a library into an org and transfers have a time limit so we usually coordinate transfers via slack. If you want to DM an email address on twitter ( same name as github ), i'll get you invited to the Webpack slack and you can @ me when you have a moment to get this moved.

Once it's there & depending on the desired main option, i'll get the proper permissions set, enable travis / codecov and update the service URLs.

**Comment by jdalton** [comment]
Thank you @d3viant0ne!

The loader is super bare-bones. It essentially just calls the built-in node module `zlib.gunzip`.
Since this is such a small loader, ~10 LOC, I don't anticipate much of a support burden.
I'm happy to be hands off but still have the maintainer bit to tackle any issues/support needs.

I've joined the webpack slack so we can coordinate transfer. ✨

**Comment by jdalton** [comment]
I've joined the webpack slack so we can coordinate transfer. ✨

**Comment by joshwiens** [comment]
- Permissions set.
- CLA Enabled.
- Travis Enabled.
- Codecov.io Enabled.
- Master branch protected w/ applicable status checks.

Done & Done, Cheers :)
