### ISSUE TITLE
RFC: Namespace Consistency

### ISSUE THREAD

**Issue by zhenyulin** [webpack-contrib/organization#11]
How about update the package name to `webpack-some-loader` and `webpack-some-plugin`? At the moment, the webpack plugins/loaders namespace isn't very consistent. In comparison, babel, eslint, react, redux all have the namespace in a consistent convention, helping make the dependency tree clean.

[see webpack-contrib/style-loader/#239](https://github.com/webpack-contrib/style-loader/issues/239)
#8

**Comment by joshwiens** [comment]
If we were to consider changing the name of all 58 libs currently living under `webpack-contrib`, scoping the packages to `@webpack/libName` & `@webpack-contrib/libName` would be the way to go for both a maintainers and a consumers point of view.

The `benefits` 

- You get a tidy `package.json` with all things webpack in a consistent block
- People new to webpack know where to look for their webpack dependencies without having to know if it is or isn't webpack related.
- Simplifies finding the same on something like npmjs.com as everything would have the same scope || starting string.
- Applies all of the above to your installed dependency tree, simplifying imports and clicking through the tree manually.

The `down sides`

- It would literally `require package & config updates to every webpack driven application in existence`.
- We only control a small portion of the total number of webpack loaders in plugins in webpack-contrib, possibly making this more confusing than it would be helpful.
- slapping `webpack-` or `@webpack || @webpack-contrib` in front of all the loaders & plugins makes the names longer, people will absolutely gripe about that.
- It further complicates the incoming transfer process for libs being moved into `webpack-contrib`.
- If would also require renaming all of the repos you republish if you went the convention route with `webpack-`. Mismatched repo name vs. package name is an anti-pattern.
- CI / CD updates for maintainers on every loader name change you make ( Travis, Codecov, Codeclimate, everything else ).

IMO if you look at the potential benefits vs. potential effort to the developer community & major consuming libs ( angular/cli & create-react-app ) and their consumers renaming || scoping packages would require a major effort across the entire webpack ecosystem to get it done and unfortunately once it was we would have only solved a small portion of the problem.

While I personally agree that we have outgrown the `someLib-loader & someLib-plugin` convention, the benefits to changing that at this point are far outweighed by the amount of effort required to change it.

**Comment by TheLarkInn** [comment]
@zhenyulin your idea really is a great, however because of the conventional roots we have in our ecosystem, it would really set users at a workflow disadvantage in a time where we can't really afford it.

If we we're to make a change like this, we would want to architect it around an extremely large breaking change in [core](webpack/webpack). This way there is a discernible, clear break from 2.x, or 3.x to something else. Even then I'm not reallly a huge fan of changing the established conventions unless we do a huge package, or DX overhaul. I'd vote we table this for now.

**Comment by zhenyulin** [comment]
I'm aware that it is not easy to migrate legacy code to a new name convention, but I was wondering if those packages can be published under both names so that people can start using consistent namespace without breaking the existing code base?

**Comment by joshwiens** [comment]
Regardless of initially or eventually, it's still breaking. We have discussed this a few times in `webpack-contrib` and while we may scope all of the Webpack libs at some point, it is certainly not going to happen anytime soon.

Currently, the benefits don't outweigh the communities effort to change over and there will almost certainly be unforeseen side effects somewhere.
