### ISSUE TITLE
RFC: Add support for `package-lock.json` (npm@5)

### ISSUE THREAD

**Issue by michael-ciniawsky** [webpack-contrib/organization#13]
Need to decide at an org level what we are going to do here.

**Comment by joshwiens** [comment]
A few things of note...

- Currently NPM v5.x & Yarn@latest don't play well together
- Two lock files is a bit silly, my preference would be to just stick with npm.

Pro / Con

- If we are going to switch, now would be the time to do it before we have a ton of updates to do.
- npm@5 can be installed if needed for the 4.3 / 6 builds in travis.
- Using npm@5 / npm@3 is backwards compatible to users, if 5 is installed the lock file will be used.
- We mainly use Yarn for the install speed increase, npm is now as fast if not faster.
- I personally prefer not having to bounce between yarn & npm for local dev. Single command works in any case regardless of which version ( kind of degrades gracefully ).

**Comment by bebraw** [comment]
Yeah, I would rather go with npm as well and drop Yarn from defaults.

**Comment by joshwiens** [comment]
That would be my choice, the question is really do we install npm@5 for all versions in .travis.yml or just for 8.

I haven't tried or even checked if you can use npm@5 with nodejs 4.3.

**Comment by bebraw** [comment]
That's a good question. How time critical is this? Can we revisit this again after we drop Node 4?

**Comment by sapegin** [comment]
There’s actually a pull request for that: https://github.com/webpack-contrib/webpack-defaults/pull/58 ;-)

**Comment by joshwiens** [comment]
@bebraw - Dropping node 4 is going to be a while unfortunately. 

From the npm docs...

![screen shot 2017-06-06 at 2 58 21 pm](https://user-images.githubusercontent.com/8420490/26849160-b7c7df5e-4ac8-11e7-9a19-8683d36d670f.png)

So for the sake of simplicity, might as well just install npm@5 in `before_install` and keep it simple.
