### ISSUE TITLE
Moving webpack-bundle-analyzer under webpack-contrib organization

### ISSUE THREAD

**Issue by valscion** [webpack-contrib/organization#15]
Hi folks!

@th0r and me have been discussing transfer of https://github.com/th0r/webpack-bundle-analyzer under a webpack organization in GitHub.

I asked @TheLarkInn whether this would be a good idea and he said yes, and eventually asked me to create an issue here so we could go through the process of what this transference would mean :relaxed:

As I understand it, there has been lots of decisions made in https://github.com/webpack-contrib/organization/issues/1 that we might need to apply in https://github.com/th0r/webpack-bundle-analyzer.

So, what do you want to know? And what would we need to do?

**Comment by valscion** [comment]
One reason why this is a good time to do the transition is that I am currently going over a big upgrade in `webpack-bundle-analyzer` to enable custom visualization/reporter packages: https://github.com/th0r/webpack-bundle-analyzer/pull/97

I envision that we will see many different kinds of bundle visualizations and tools pop up that would largely benefit from this. I'd love to see people go and make the wildest and funkiest visualizations they want to with quality data containing post-minification and post-gzip sizes.

**Comment by joshwiens** [comment]
Done & done
