### ISSUE TITLE
What about creating a positive and inclusive environment?

### ISSUE THREAD

**Issue by maximandrews** [webpack-contrib/organization#20]
Hi there.

I was wondering if there are any thought on adapting [Contributor Covenant Code of Conduct](https://www.contributor-covenant.org/version/1/4/code-of-conduct.html) or similar to create positive, inclusive and contributions welcoming environment?

IMHO it is nice to have one and to enforce it for all members and collaborators.

What are your thought on this?

**Comment by alexander-akait** [comment]
@maximandrewz We already works under JS Foundation and here code of conduct https://js.foundation/community/code-of-conduct, i think it is good idea add `CODE_OF_CODUCT.md` in each repo

**Comment by michael-ciniawsky** [comment]
We should add the JSF `CODE_OF_CONDUCT.md` to repos via `webpack-defaults`. I will open a tracking issue in `webpack-defaults` about it

@maximandrewz Is there anything else in particular you think is important to create a positive and inclusive enviroment ? If not I'm going to close this in favor of the tracking issues once opened :)

**Comment by michael-ciniawsky** [comment]
I'm closing this for now, feel free to reopen if you still have something in mind which should be addressed :)
