### ISSUE TITLE
JavaScript Foundation CLA assistant

### ISSUE THREAD

**Issue by joshwiens** [webpack-contrib/organization#4]
To enable the CLA bot, updates are required organization wide to bring the `webpack-contrib` repos inline with the JS foundation requirements.

**_Licensing_**

- Anything previously under the webpack copyright, needs to have the proper JSF license if it doesn't ( anyone can commit ).

- For any new additions / acquisitions (see below)  the license change to JSF needs to be committed by the existing copyright holder.

_Repos needing attention_

- ~~npm-install: webpack-contrib/npm-install-webpack-plugin#106~~

All other repos are either up to date or have an open pull request (see below)

**_Maintainers_**

- Any repo that had just Tobias listed as the maintainer was updated to include the entire admin team
- Any repo with a non-standard readme format was updated to the defined `webpack-contrib`

All repos are either up to date or have an open pull request (see below)

**_Attic_**

- Add `webpack-attic` topic to repo
- Add `UNMAINTAINED` to repo Title
- Add `UNMAINTAINED` to `README.md` heading

_Repos to be mothballed_

- component-webpack-plugin
- coverjs-loader
-  i18n-loader

> JSF requirement: Moving it to an "attic" of sorts if it becomes abandoned / unmaintained will be important.

**Comment by joshwiens** [comment]
**Verify clear display of maintainers for all Webpack-Contrib Repos & update readme to standard**

- [x] awesome-webpack
- [x] mocha-loader - https://github.com/webpack-contrib/mocha-loader/pull/55
- [x] exports-loader - https://github.com/webpack-contrib/exports-loader/pull/11
- [x] coffee-loader - https://github.com/webpack-contrib/coffee-loader/pull/23
- [x] uglifyjs-webpack-plugin - https://github.com/webpack-contrib/uglifyjs-webpack-plugin/pull/13
- [x] html-loader
- [x] style-loader
- [x] worker-loader - https://github.com/webpack-contrib/worker-loader/pull/49
- [x] extract-text-webpack-plugin - https://github.com/webpack-contrib/extract-text-webpack-plugin/pull/419
- [x] css-loader
- [x] source-map-loader - https://github.com/webpack-contrib/source-map-loader/pull/27
- [x] expose-loader - https://github.com/webpack-contrib/expose-loader/pull/34
- [x] less-loader
- [x] sass-loader
- [x] webpack-canary - https://github.com/webpack-contrib/webpack-canary/pull/17
- [x] karma-webpack
- [x] jshint-loader - https://github.com/webpack-contrib/jshint-loader/pull/34
- [x] component-webpack-plugin - `move to attic`
- [x] grunt-webpack - https://github.com/webpack-contrib/grunt-webpack/pull/120
- [x] webpack-defaults
- [x] file-loader
- [x] url-loader
- [x] json5-loader
- [x] purifycss-webpack - https://github.com/webpack-contrib/purifycss-webpack/pull/80
- [x] npm-install-webpack-plugin - https://github.com/webpack-contrib/npm-install-webpack-plugin/pull/107
- [x] bundle-loader - https://github.com/webpack-contrib/bundle-loader/pull/35
- [x] schema-utils
- [x] babel-preset-webpack
- [x] eslint-config-webpack
- [x] json-loader
- [x] raw-loader
- [x] node-loader
- [x] i18n-webpack-plugin - https://github.com/webpack-contrib/i18n-webpack-plugin/pull/35
- [x] compression-webpack-plugin - https://github.com/webpack-contrib/compression-webpack-plugin/pull/42
- [x] imports-loader - https://github.com/webpack-contrib/imports-loader/pull/40
- [x] transform-loader - https://github.com/webpack-contrib/transform-loader/pull/17
- [x] coffee-redux-loader - https://github.com/webpack-contrib/coffee-redux-loader/pull/6
- [x] val-loader - https://github.com/webpack-contrib/val-loader/pull/9
- [x] script-loader - https://github.com/webpack-contrib/script-loader/pull/26
- [x] react-proxy-loader - https://github.com/webpack-contrib/react-proxy-loader/pull/23
- [x] null-loader - https://github.com/webpack-contrib/null-loader/pull/5
- [x] coverjs-loader - `move to attic`
- [x] multi-loader - https://github.com/webpack-contrib/multi-loader/pull/4
- [x] i18n-loader - `move to attic`

**Comment by joshwiens** [comment]
**Verify or update of the JavaScript Foundation License for all `Webpack Contrib` repos**

- [x] awesome-webpack license verification
- [x] mocha-loader license verification
- [x] exports-loader license verification
- [x] coffee-loader - https://github.com/webpack-contrib/coffee-loader/pull/23
- [x] uglifyjs-webpack-plugin `COPYRIGHT TRANSFER` commit by @bebraw https://github.com/webpack-contrib/uglifyjs-webpack-plugin/pull/12
- [x] html-loader - https://github.com/webpack-contrib/html-loader/pull/111
- [x] style-loader license verification
- [x] worker-loader - https://github.com/webpack-contrib/worker-loader/pull/48
- [x] extract-text-webpack-plugin license verification
- [x] css-loader license verification
- [x] source-map-loader license verification
- [x] expose-loader - https://github.com/webpack-contrib/expose-loader/pull/33
- [x] less-loader license verification
- [x] sass-loader `COPYRIGHT TRANSFER` commit by @jhnns https://github.com/webpack-contrib/sass-loader/pull/385
- [x] webpack-canary `COPYRIGHT TRANSFER` commit by @alistairjcbrown https://github.com/webpack-contrib/webpack-canary/pull/16
- [x] karma-webpack license verification
- [x] jshint-loader - https://github.com/webpack-contrib/jshint-loader/pull/33
- [x] component-webpack-plugin - https://github.com/webpack-contrib/component-webpack-plugin/pull/10
- [x] grunt-webpack license verification
- [x] webpack-defaults license verification
- [x] file-loader license verification
- [x] url-loader license verification
- [x] json5-loader - https://github.com/webpack-contrib/json5-loader/pull/19
- [x] purifycss-webpack `COPYRIGHT TRANSFER` commit by @kennyt https://github.com/webpack-contrib/purifycss-webpack/pull/81
- [x] babili-webpack-plugin `COPYRIGHT TRANSFER` commit by @boopathi https://github.com/webpack-contrib/babili-webpack-plugin/pull/29
- [x] svg-inline-loader `COPYRIGHT TRANSFER` commit by @sairion https://github.com/webpack-contrib/svg-inline-loader/commit/7183d48aacafc1e5f705cb9c9c36e3b2cee39ebd
- [x] npm-install-webpack-plugin `COPYRIGHT TRANSFER` commit by @ericclemmons https://github.com/webpack-contrib/npm-install-webpack-plugin/issues/106
- [x] bundle-loader - https://github.com/webpack-contrib/bundle-loader/pull/34
- [x] schema-utils license verification
- [x] babel-preset-webpack license verification
- [x] eslint-config-webpack license verification
- [x] json-loader license verification
- [x] raw-loader license verification
- [x] node-loader license verification
- [x] i18n-webpack-plugin - https://github.com/webpack-contrib/i18n-webpack-plugin/pull/34
- [x] compression-webpack-plugin - https://github.com/webpack-contrib/compression-webpack-plugin/pull/41
- [x] imports-loader license verification
- [x] transform-loader - https://github.com/webpack-contrib/transform-loader/pull/16
- [x] coffee-redux-loader 
- [x] val-loader - https://github.com/webpack-contrib/val-loader/pull/8
- [x] script-loader - https://github.com/webpack-contrib/script-loader/pull/26
- [x] react-proxy-loader 
- [x] null-loader - https://github.com/webpack-contrib/null-loader/pull/4
- [x] coverjs-loader `move to attic`
- [x] multi-loader - https://github.com/webpack-contrib/multi-loader/pull/3
- [x] i18n-loader `move to attic`

**Comment by joshwiens** [comment]
**Verify Protected Master Branch and required CLA Check**

- [x] awesome-webpack
- [x] mocha-loader
- [x] exports-loader
- [x] coffee-loader
- [x] uglifyjs-webpack-plugin
- [x] html-loader
- [x] style-loader
- [x] worker-loader
- [x] extract-text-webpack-plugin
- [x] css-loader
- [x] source-map-loader
- [x] expose-loader
- [x] less-loader
- [x] sass-loader
- [x] webpack-canary
- [x] karma-webpack
- [x] jshint-loader
- [x] component-webpack-plugin
- [x] grunt-webpack
- [x] webpack-defaults
- [x] file-loader
- [x] url-loader
- [x] json5-loader
- [x] purifycss-webpack
- [x] npm-install-webpack-plugin
- [x] bundle-loader
- [x] schema-utils
- [x] babel-preset-webpack
- [x] eslint-config-webpack
- [x] json-loader
- [x] raw-loader
- [x] node-loader
- [x] i18n-webpack-plugin
- [x] compression-webpack-plugin
- [x] imports-loader 
- [x] transform-loader
- [x] coffee-redux-loader
- [x] val-loader
- [x] script-loader
- [x] react-proxy-loader 
- [x] null-loader
- [x] multi-loader

**Comment by ericclemmons** [comment]
Resolving this now.

**Comment by ericclemmons** [comment]
@d3viant0ne Thanks for your help on this one!  `npm-install-webpack-plugin` is all checked off!

**Comment by d3viant0ne** [comment]
No problem. And with that, done & done

**Comment by joshwiens** [comment]
**Library license field type**

- [x] awesome-webpack - `license: CC0-1.0`
- [x] mocha-loader - `license: MIT`
- [x] exports-loader - `license: MIT`
- [x] coffee-loader - `license: MIT`
- [x] uglifyjs-webpack-plugin - `license: MIT`
- [x] html-loader - `license: MIT`
- [x] style-loader - `license: MIT`
- [x] worker-loader - `license: MIT`
- [x] extract-text-webpack-plugin - `license: MIT`
- [x] css-loader - `license: MIT`
- [x] source-map-loader - `license: MIT`
- [x] expose-loader - `license: MIT`
- [x] less-loader - `license: MIT`
- [x] sass-loader - `license: MIT`
- [ ] webpack-canary - `license: ISC`
- [x] karma-webpack - `license: MIT`
- [x] jshint-loader - `license: MIT`
- [x] component-webpack-plugin - `license: MIT`
- [x] grunt-webpack - `license: MIT`
- [x] webpack-defaults - `license: MIT`
- [x] file-loader - `license: MIT`
- [x] url-loader - `license: MIT`
- [x] json5-loader - `license: MIT` 
- [ ] purifycss-webpack - `license: ISC`
- [x] npm-install-webpack-plugin - `license: MIT`
- [x] bundle-loader - `license: MIT`
- [x] restyle-loader - `license: MIT`
- [x] schema-utils - `license: MIT`
- [x] babel-preset-webpack - `license: MIT`
- [x] babili-webpack-plugin - `license: MIT`
- [x] eslint-config-webpack - `license: MIT`
- [x] yaml-frontmatter-loader - `license: MIT`
- [x] webpack-contrib-sync - `license: MIT`  
- [x] json-loader - `license: MIT`
- [x] raw-loader - `license: MIT`
- [x] node-loader - `license: MIT`
- [x] i18n-webpack-plugin - `license: MIT`
- [x] compression-webpack-plugin - `license: MIT`
- [x] imports-loader - `license: MIT` 
- [x] transform-loader - `license: MIT`  
- [x] coffee-redux-loader - `license: MIT`
- [x] val-loader - `license: MIT`
- [x] script-loader - `license: MIT`
- [x] react-proxy-loader - `license: MIT`
- [x] null-loader - `license: MIT`
- [x] multi-loader - `license: MIT`
- [x] svg-inline-loader - `license: MIT`
- [x] coverjs-loader - `license: MIT`
- [x] i18n-loader - `license: MIT`
