### ISSUE TITLE
Ensure all contrib repositories have `engines` defined

### ISSUE THREAD

**Issue by joshwiens** [webpack-contrib/organization#7]
**We have more than a few repos that don't have the engines field designated in the `package.json`**

- Update all contrib repos with the same supported engines as `webpack/webpack`

```
  "engines": {
    "node": ">=4.3.0 <5.0.0 || >=5.10"
  },
```

**Comment by sapegin** [comment]
Any reason to skip 5.0—5.9? I’ve sent a PR to webpack-defaults.

**Comment by joshwiens** [comment]
There is a reason for it based on issues with those versions & webpack. I don't know what they are exactly, only that they exist.

**Comment by sapegin** [comment]
OK, I’ll add a comment in webpack-defaults then ;-)

**Comment by sukrosono** [comment]
I would suggest a done-list on first post, so we can track remaining work and it's progress.

**Comment by joshwiens** [comment]
Engines ranges come with webpack-defaults. Which is trackable here https://github.com/orgs/webpack-contrib/projects/5

**Comment by sukrosono** [comment]
it lead me 404, it's restricted scope?
Nvm if you already have the checklist :smile: .

**Comment by joshwiens** [comment]
Organization project so probably but none the less, there is tracking across every project under contrib

**Comment by michael-ciniawsky** [comment]
Resolved by/in `webpack-defaults`
